inputs:
  name: 
    MAVEN_ARGS: 'Your maven arguements for release-start/finish'
    default: '-DreleaseVersion=$${parsedVersion.majorVersion}.$${parsedVersion.minorVersion}.$${parsedVersion.incrementalVersion} -DdevelopmentVersion=$${parsedVersion.majorVersion}.$${parsedVersion.minorVersion}.$${parsedVersion.nextIncrementalVersion}-SNAPSHOT -DallowUntracked=true $MAVEN_OPTS'
runs:
  using: "composite"
  steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
    - name: Build with Maven
      run: |
        git config --global user.name "ais-swe-ci"
        git config --global user.email "aitci@psu.edu"
        git fetch
        git checkout master
        git checkout develop
        echo -n $SIGNING_PRIVATE | base64 -di > ~/private.asc
        gpg --pinentry-mode loopback --batch --no-tty --yes --passphrase $SIGNING_PASSPHRASE --import ~/private.asc
        mvn -B clean build-helper:parse-version jgitflow:release-start ${{ inputs.MAVEN_ARGS }}
        mvn -B jgitflow:release-finish -Dgpg.passphrase=$SIGNING_PASSPHRASE ${{ inputs.MAVEN_ARGS }}
        git checkout develop
        git commit --amend -m '[skip-ci] Updating develop poms back to pre merge state'
        git push --all --follow-tags
      env:
        SIGNING_PRIVATE: ${{ secrets.SIGNING_PRIVATE }}
        SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
        OSSRH_USERNAME: aitci
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_ARGS: -DallowSnapshots=false -DallowUntracked=true -Psign-artifacts