name: Java Build

on:
  push:
    branches: 
    - develop
    - master
    - 'feature/**'
    tags:
    - '*'

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') ||
      !contains(github.event.head_commit.message, 'release:')

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD

    - name: Build with Maven
      run: |
        echo -n $SIGNING_PRIVATE | base64 -di > ~/private.asc
        gpg --pinentry-mode loopback --batch --no-tty --yes --passphrase $SIGNING_PASSPHRASE --import ~/private.asc
        gpg -k
        mvn -B deploy -Psign-artifacts -Dgpg.passphrase=$SIGNING_PASSPHRASE
      env:
       SIGNING_PRIVATE: ${{ secrets.SIGNING_PRIVATE }}
       SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
       OSSRH_USERNAME: aitci
       OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  
  release_patch:
    if: "contains(github.event.head_commit.message, 'release: patch')"

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD

    - name: Increment Step Patch
      uses: rickstaa/action-get-semver@v1
      id: get_semver
      with: 
        bump_level: "patch"


    - name: Patch Release with Maven
      shell: bash
      run: |
        git config --global user.name "ais-swe-ci"
        git config --global user.email "aitci@psu.edu"
        git checkout develop
        echo "git log"
        git log
        echo -n $SIGNING_PRIVATE | base64 -di > ~/private.asc
        gpg --pinentry-mode loopback --batch --no-tty --yes --passphrase $SIGNING_PASSPHRASE --import ~/private.asc
        mvn -B clean build-helper:parse-version jgitflow:release-start -DreleaseVersion=${steps.get_semver.outputs.current_version} -DdevelopmentVersion=${{ steps.get_semver.outputs.next_version }}-SNAPSHOT -DallowUntracked=true -DallowSnapshots=false -DallowUntracked=true -Psign-artifacts
        mvn -B jgitflow:release-finish -Dgpg.passphrase=$SIGNING_PASSPHRASE -DreleaseVersion=${steps.get_semver.outputs.current_version} -DdevelopmentVersion=${{ steps.get_semver.outputs.next_version }}-SNAPSHOT -DallowUntracked=true -DallowSnapshots=false -DallowUntracked=true -Psign-artifacts
        git checkout develop
        git commit --amend -m '[skip-ci] Updating develop poms back to pre merge state'
        git push --all --follow-tags
      env:
        SIGNING_PRIVATE: ${{secrets.SIGNING_PRIVATE}}
        SIGNING_PASSPHRASE: ${{secrets.SIGNING_PASSPHRASE}}
        OSSRH_USERNAME: aitci
        OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
        releaseVersion: ${{github.events.input.releaseVersion}}
        nextVersion: ${{github.events.input.nextVersion}}
  
  release_minor:
    if: "contains(github.event.head_commit.message, 'release: minor')"
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD

    - name: Increment Step Minor
      uses: rickstaa/action-get-semver@v1
      id: get_semver
      with: 
        bump_level: "minor"

    - name: Minor Release with Maven
      shell: bash
      run: |
        git config --global user.name "ais-swe-ci"
        git config --global user.email "aitci@psu.edu"
        git checkout develop
        echo "git log"
        git log
        echo -n $SIGNING_PRIVATE | base64 -di > ~/private.asc
        gpg --pinentry-mode loopback --batch --no-tty --yes --passphrase $SIGNING_PASSPHRASE --import ~/private.asc
        mvn -B clean build-helper:parse-version jgitflow:release-start -DreleaseVersion=${steps.get_semver.outputs.current_version} -DdevelopmentVersion=${{ steps.get_semver.outputs.next_version }}-SNAPSHOT -DallowUntracked=true -DallowSnapshots=false -DallowUntracked=true -Psign-artifacts
        mvn -B jgitflow:release-finish -Dgpg.passphrase=$SIGNING_PASSPHRASE -DreleaseVersion=${steps.get_semver.outputs.current_version} -DdevelopmentVersion=${{ steps.get_semver.outputs.next_version }}-SNAPSHOT -DallowUntracked=true -DallowSnapshots=false -DallowUntracked=true -Psign-artifacts
        git checkout develop
        git commit --amend -m '[skip-ci] Updating develop poms back to pre merge state'
        git push --all --follow-tags
      env:
        SIGNING_PRIVATE: ${{secrets.SIGNING_PRIVATE}}
        SIGNING_PASSPHRASE: ${{secrets.SIGNING_PASSPHRASE}}
        OSSRH_USERNAME: aitci
        OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
        releaseVersion: ${{github.events.input.releaseVersion}}
        nextVersion: ${{github.events.input.nextVersion}}
  
  release_major:
    if: "contains(github.event.head_commit.message, 'release: major')"
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD

    - name: Increment Step Major
      uses: rickstaa/action-get-semver@v1
      id: get_semver
      with: 
        bump_level: "major"

    - name: Major Release with Maven
      shell: bash
      run: |
        git config --global user.name "ais-swe-ci"
        git config --global user.email "aitci@psu.edu"
        git checkout develop
        echo "git log"
        git log
        echo -n $SIGNING_PRIVATE | base64 -di > ~/private.asc
        gpg --pinentry-mode loopback --batch --no-tty --yes --passphrase $SIGNING_PASSPHRASE --import ~/private.asc
        mvn -B clean build-helper:parse-version jgitflow:release-start -DreleaseVersion=${steps.get_semver.outputs.current_version} -DdevelopmentVersion=${{ steps.get_semver.outputs.next_version }}-SNAPSHOT -DallowUntracked=true -DallowSnapshots=false -DallowUntracked=true -Psign-artifacts
        mvn -B jgitflow:release-finish -Dgpg.passphrase=$SIGNING_PASSPHRASE -DreleaseVersion=${steps.get_semver.outputs.current_version} -DdevelopmentVersion=${{ steps.get_semver.outputs.next_version }}-SNAPSHOT -DallowUntracked=true -DallowSnapshots=false -DallowUntracked=true -Psign-artifacts
        git checkout develop
        git commit --amend -m '[skip-ci] Updating develop poms back to pre merge state'
        git push --all --follow-tags
      env:
        SIGNING_PRIVATE: ${{secrets.SIGNING_PRIVATE}}
        SIGNING_PASSPHRASE: ${{secrets.SIGNING_PASSPHRASE}}
        OSSRH_USERNAME: aitci
        OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
        releaseVersion: ${{github.events.input.releaseVersion}}
        nextVersion: ${{github.events.input.nextVersion}}