name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      releasetype:
        description: 'Release Type: Major/Minor/Patch (default Patch)'
        required: true
        default: 'Patch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Major Release
      if: contains(github.event.releasetype, 'Major')
      uses: /.github/actions/release.yaml
      with:
        MAVEN_ARGS: -DreleaseVersion=$${parsedVersion.nextMajorVersion}.0.0 -DdevelopmentVersion=$${parsedVersion.nextMajorVersion}.0.1-SNAPSHOT -DallowUntracked=true $MAVEN_OPTS
    - name: Minor Release
      if: contains(github.event.releasetype, 'Minor')
      uses: /.github/actions/release.yaml
      with:
        MAVEN_ARGS: -DreleaseVersion=$${parsedVersion.majorVersion}.$${parsedVersion.nextMinorVersion}.0 -DdevelopmentVersion=$${parsedVersion.majorVersion}.$${parsedVersion.nextMinorVersion}.1-SNAPSHOT -DallowUntracked=true $MAVEN_OPTS
    - name: Patch Release
      if: contains(github.event.releasetype, 'Patch')
      uses: /.github/actions/release.yaml
      with:
        MAVEN_ARGS: -DreleaseVersion=$${parsedVersion.majorVersion}.$${parsedVersion.minorVersion}.$${parsedVersion.incrementalVersion} -DdevelopmentVersion=$${parsedVersion.majorVersion}.$${parsedVersion.minorVersion}.$${parsedVersion.nextIncrementalVersion}-SNAPSHOT -DallowUntracked=true $MAVEN_OPTS

    
    # TODO: add steps to:
    # - Version POMs
    # - Update POM to next Snapshot version (on develop branch)
    # - Add released artifacts to the release (publish) that started this build
